FROM alisonalonso/java:ubuntu
MAINTAINER Alison Alonso

# Dependencies...
RUN apt-get update && apt-get install -y --force-yes ant rsync

# Getting...
ENV FLEX_SDK_DIR=apache-flex-sdk FLEX_SDK_FILE=${FLEX_SDK_DIR}-bin.tar.gz
ADD http://mirror.nbtelecom.com.br/apache/flex/4.15.0/binaries/${FLEX_SDK_FILE} /

# Extracting...
RUN tar -xzvf $FLEX_SDK_FILE
RUN mv ${FLEX_SDK_DIR}-bin ${FLEX_SDK_DIR}

# Installing...
WORKDIR /${FLEX_SDK_DIR}
RUN ant -f installer.xml -Dinput.air.download=y -Dinput.flash.download=y -Dinput.fontswf.download=y

# Configuring...
ENV FLEX_HOME /${FLEX_SDK_DIR}
ENV PATH=$PATH:$FLEX_HOME/bin

WORKDIR /app
