FROM ubuntu
MAINTAINER Alison Alonso

# Dependencies...
RUN apt-get update && \
    apt-get install -y --allow-change-held-packages openjdk-8-jdk ant rsync curl

# Getting...
ENV FLEX_SDK_DIR=apache-flex-sdk \
    FLEX_VERSION=4.16.1
ENV FLEX_SDK_FILE=${FLEX_SDK_DIR}-${FLEX_VERSION}-bin.tar.gz \
    FLEX_HOME=/opt/${FLEX_SDK_DIR}
ENV PATH=$PATH:$FLEX_HOME/bin

RUN export APACHE_MIRROR=$(curl -s 'http://www.apache.org/dyn/closer.cgi?as_json=1' | \
    grep "preferred" | cut -d ':' -f3 | cut -d'"' -f1 | awk -F// '{print $NF}' | sed 's/.$//') && \
    curl -o /${FLEX_SDK_FILE} http://${APACHE_MIRROR}/flex/${FLEX_VERSION}/binaries/${FLEX_SDK_FILE}

# Installing...
RUN tar -xzf ${FLEX_SDK_FILE} && \
    mv ${FLEX_SDK_DIR}-${FLEX_VERSION}-bin /opt/${FLEX_SDK_DIR} && \
    cd ${FLEX_HOME} && \
    ant -f installer.xml -Dinput.air.download=y -Dinput.flash.download=y -Dinput.fontswf.download=y

WORKDIR /app
